# Generated by Django 4.2 on 2023-04-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
