# Generated by Django 4.2 on 2023-04-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_permission_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='organisation',
        ),
        migrations.AddField(
            model_name='permission',
            name='organisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.organisation'),
        ),
    ]
