# Generated by Django 4.2 on 2023-04-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_permission_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
