# Generated by Django 4.2 on 2023-04-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_permission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.AddField(
            model_name='permission',
            name='organisation_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='permission',
            name='user_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
