# Generated by Django 4.2 on 2023-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_permission_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='access_level',
            field=models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('READANDWRITE', 'Read and Write'), ('ADMIN', 'Admin')], default='READ', max_length=20),
        ),
    ]
